version: '2'

services:

  php:
    build:
      context: ./.docker/images/php
    volumes:   
      - ./apps/php:/var/www/php

  python:
    build:
      context: ./.docker/images/python
    working_dir: /var/www/python
    volumes:
      - ./apps/python:/var/www/python      
    ports:
      - "8082:9001"

  nginx:
    build:
      context: ./.docker/images/nginx
    volumes:
      - ./apps/html:/var/www/html      
      - ./apps/php:/var/www/php
    ports:
      - "8080:80"
      - "8081:81"